INFO 2023-10-16 14:17:59,964 django.utils.autoreload MainThread 21296 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 4736 Watching for file changes with StatReloader
INFO 2023-10-16 14:18:20,551 django.utils.autoreload MainThread 21296 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 4736 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course_u\settings.py changed, reloading.
INFO 2023-10-16 14:18:23,433 django.utils.autoreload MainThread 3700 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 18632 Watching for file changes with StatReloader
INFO 2023-10-16 14:18:40,316 django.server Thread-1 19344 basehttp basehttp.py 212 django.server log_message 18632 "GET /login_user/ HTTP/1.1" 200 11354
INFO 2023-10-16 14:18:40,512 django.server Thread-1 19344 basehttp basehttp.py 212 django.server log_message 18632 "GET /static/css/forgot.css HTTP/1.1" 200 1386
INFO 2023-10-16 14:18:40,553 django.server Thread-2 4956 basehttp basehttp.py 212 django.server log_message 18632 "GET /static/css/test.css HTTP/1.1" 304 0
INFO 2023-10-16 14:18:40,618 django.server Thread-3 19908 basehttp basehttp.py 212 django.server log_message 18632 "GET /static/css/login.css HTTP/1.1" 200 1696
INFO 2023-10-16 14:18:40,639 django.server Thread-4 22828 basehttp basehttp.py 212 django.server log_message 18632 "GET /static/images/login.jpg HTTP/1.1" 200 166925
WARNING 2023-10-16 14:18:42,018 django.request Thread-4 22828 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:18:42,029 django.server Thread-4 22828 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:18:42,177 django.request Thread-3 19908 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:18:42,179 django.server Thread-3 19908 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:18:42,969 django.request Thread-5 11032 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:18:42,971 django.server Thread-5 11032 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
INFO 2023-10-16 14:18:48,724 django.server Thread-5 11032 basehttp basehttp.py 212 django.server log_message 18632 "POST /login_user/ HTTP/1.1" 302 0
INFO 2023-10-16 14:18:49,179 django.server Thread-5 11032 basehttp basehttp.py 212 django.server log_message 18632 "GET /home HTTP/1.1" 200 32178
INFO 2023-10-16 14:18:49,278 django.server Thread-5 11032 basehttp basehttp.py 212 django.server log_message 18632 "GET /static/css/home.css HTTP/1.1" 200 851
WARNING 2023-10-16 14:18:49,291 django.server Thread-6 8800 basehttp basehttp.py 212 django.server log_message 18632 "GET /static/css/test%20.css HTTP/1.1" 404 1800
WARNING 2023-10-16 14:18:49,807 django.request Thread-5 11032 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:18:49,809 django.server Thread-5 11032 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 14:18:50,802 django.request Thread-5 11032 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:18:50,804 django.server Thread-5 11032 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
INFO 2023-10-16 14:18:53,070 django.server Thread-7 492 basehttp basehttp.py 212 django.server log_message 18632 "GET /field/1/ HTTP/1.1" 200 2747
INFO 2023-10-16 14:18:53,296 django.server Thread-7 492 basehttp basehttp.py 212 django.server log_message 18632 "GET /__debug__/history_sidebar/?store_id=154f77eec2ba4dec93caa8144c1eddbd HTTP/1.1" 200 9090
INFO 2023-10-16 14:18:54,078 django.server Thread-7 492 basehttp basehttp.py 212 django.server log_message 18632 "GET /field/2/ HTTP/1.1" 200 1857
INFO 2023-10-16 14:18:54,309 django.server Thread-7 492 basehttp basehttp.py 212 django.server log_message 18632 "GET /__debug__/history_sidebar/?store_id=18379faa7e854bdab22eefb5dc16fc99 HTTP/1.1" 200 9090
INFO 2023-10-16 14:19:03,482 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /admin_home/ HTTP/1.1" 200 19161
WARNING 2023-10-16 14:19:04,032 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:04,046 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:19:04,997 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:04,998 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
INFO 2023-10-16 14:19:06,383 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /admin_home/ HTTP/1.1" 200 19161
WARNING 2023-10-16 14:19:06,921 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:06,923 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:19:07,875 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:07,876 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
INFO 2023-10-16 14:19:09,565 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /admin_home/ HTTP/1.1" 200 19161
WARNING 2023-10-16 14:19:10,030 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:10,032 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
WARNING 2023-10-16 14:19:10,999 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:11,001 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
INFO 2023-10-16 14:19:11,823 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /profile/ HTTP/1.1" 200 11814
WARNING 2023-10-16 14:19:12,302 django.request Thread-8 15320 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:12,303 django.server Thread-8 15320 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:19:13,312 django.request Thread-9 23164 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:13,314 django.server Thread-9 23164 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
INFO 2023-10-16 14:19:14,197 django.server Thread-9 23164 basehttp basehttp.py 212 django.server log_message 18632 "GET /home HTTP/1.1" 200 31882
WARNING 2023-10-16 14:19:14,284 django.server Thread-9 23164 basehttp basehttp.py 212 django.server log_message 18632 "GET /static/css/test%20.css HTTP/1.1" 404 1800
WARNING 2023-10-16 14:19:14,759 django.request Thread-10 15628 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:14,764 django.server Thread-10 15628 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:19:15,682 django.request Thread-10 15628 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:15,684 django.server Thread-10 15628 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
INFO 2023-10-16 14:19:15,832 django.server Thread-10 15628 basehttp basehttp.py 212 django.server log_message 18632 "GET /profile/ HTTP/1.1" 200 11814
WARNING 2023-10-16 14:19:16,313 django.request Thread-10 15628 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:16,314 django.server Thread-10 15628 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17077
WARNING 2023-10-16 14:19:17,308 django.request Thread-10 15628 log log.py 241 django.request log_response 18632 Not Found: /favicon.ico
WARNING 2023-10-16 14:19:17,310 django.server Thread-10 15628 basehttp basehttp.py 212 django.server log_message 18632 "GET /favicon.ico HTTP/1.1" 404 17076
INFO 2023-10-16 17:49:22,892 django.utils.autoreload MainThread 18040 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 20812 Watching for file changes with StatReloader
INFO 2023-10-16 17:51:00,086 django.utils.autoreload MainThread 18040 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 20812 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course_u\settings.py changed, reloading.
INFO 2023-10-16 17:51:02,628 django.utils.autoreload MainThread 16116 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 8860 Watching for file changes with StatReloader
INFO 2023-10-16 17:51:38,237 django.utils.autoreload MainThread 16116 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 8860 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course_u\settings.py changed, reloading.
INFO 2023-10-16 17:51:45,361 django.utils.autoreload MainThread 2344 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 14196 Watching for file changes with StatReloader
INFO 2023-10-16 17:52:42,499 django.utils.autoreload MainThread 2344 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 14196 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course_u\settings.py changed, reloading.
INFO 2023-10-16 17:52:46,141 django.utils.autoreload MainThread 15260 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 19944 Watching for file changes with StatReloader
INFO 2023-10-16 17:53:17,412 django.utils.autoreload MainThread 15260 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 19944 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course_u\settings.py changed, reloading.
INFO 2023-10-16 17:53:21,356 django.utils.autoreload MainThread 18420 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 7436 Watching for file changes with StatReloader
INFO 2023-10-16 17:53:58,500 django.utils.autoreload MainThread 18420 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 7436 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course_u\settings.py changed, reloading.
INFO 2023-10-16 17:54:01,586 django.utils.autoreload MainThread 14396 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 14996 Watching for file changes with StatReloader
INFO 2023-10-16 17:54:46,889 django.utils.autoreload MainThread 14396 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 14996 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\website\views.py changed, reloading.
INFO 2023-10-16 17:54:53,116 django.utils.autoreload MainThread 1908 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 4652 Watching for file changes with StatReloader
INFO 2023-10-16 17:55:13,930 django.utils.autoreload MainThread 1908 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 4652 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\website\views.py changed, reloading.
INFO 2023-10-16 17:55:19,949 django.utils.autoreload MainThread 5656 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 21804 Watching for file changes with StatReloader
INFO 2023-10-16 17:55:50,641 django.utils.autoreload MainThread 5656 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 21804 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\website\views.py changed, reloading.
INFO 2023-10-16 17:55:53,161 django.utils.autoreload MainThread 7100 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 20568 Watching for file changes with StatReloader
INFO 2023-10-16 17:56:56,438 django.utils.autoreload MainThread 7100 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 20568 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\website\views.py changed, reloading.
INFO 2023-10-16 17:57:06,501 django.utils.autoreload MainThread 7708 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 8308 Watching for file changes with StatReloader
INFO 2023-10-16 17:58:22,544 django.utils.autoreload MainThread 7708 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 8308 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\website\views.py changed, reloading.
INFO 2023-10-16 17:58:24,845 django.utils.autoreload MainThread 9712 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 1620 Watching for file changes with StatReloader
INFO 2023-10-16 17:58:34,168 django Thread-1 10228 views views.py 34 django home 1620 User: aky is accessing home page
WARNING 2023-10-16 17:58:34,191 django Thread-1 10228 views views.py 35 django home 1620 User: aky is accessing home page
ERROR 2023-10-16 17:58:34,344 django Thread-1 10228 views views.py 36 django home 1620 User: aky is accessing home page
CRITICAL 2023-10-16 17:58:34,458 django Thread-1 10228 views views.py 37 django home 1620 User: aky is accessing home page
INFO 2023-10-16 17:58:34,797 django.server Thread-1 10228 basehttp basehttp.py 212 django.server log_message 1620 "GET /home HTTP/1.1" 200 31962
WARNING 2023-10-16 17:58:34,895 django.server Thread-1 10228 basehttp basehttp.py 212 django.server log_message 1620 "GET /static/css/test%20.css HTTP/1.1" 404 1800
INFO 2023-10-16 17:58:35,765 django.server Thread-2 17508 basehttp basehttp.py 212 django.server log_message 1620 "GET /static/images/favicon.png HTTP/1.1" 304 0
INFO 2023-10-16 19:16:03,594 django.utils.autoreload MainThread 20548 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 8624 Watching for file changes with StatReloader
INFO 2023-10-16 19:16:28,354 django.utils.autoreload MainThread 20548 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 8624 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\course_u\settings.py changed, reloading.
INFO 2023-10-16 19:16:31,425 django.utils.autoreload MainThread 12536 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 12928 Watching for file changes with StatReloader
INFO 2023-10-16 19:16:42,415 django.server Thread-1 17508 basehttp basehttp.py 212 django.server log_message 12928 "GET / HTTP/1.1" 200 9439
INFO 2023-10-16 19:16:42,559 django.server Thread-1 17508 basehttp basehttp.py 212 django.server log_message 12928 "GET /static/css/landing.css HTTP/1.1" 200 1072
INFO 2023-10-16 19:16:43,761 django.server Thread-1 17508 basehttp basehttp.py 212 django.server log_message 12928 "GET /static/images/landing2.png HTTP/1.1" 200 1935293
WARNING 2023-10-16 19:16:43,875 django.request Thread-2 19044 log log.py 241 django.request log_response 12928 Not Found: /favicon.ico
WARNING 2023-10-16 19:16:43,880 django.server Thread-2 19044 basehttp basehttp.py 212 django.server log_message 12928 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-16 19:16:44,997 django.request Thread-2 19044 log log.py 241 django.request log_response 12928 Not Found: /favicon.ico
WARNING 2023-10-16 19:16:44,997 django.server Thread-2 19044 basehttp basehttp.py 212 django.server log_message 12928 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-16 19:17:11,310 django.server Thread-3 21932 basehttp basehttp.py 212 django.server log_message 12928 "GET /login_user/ HTTP/1.1" 302 0
INFO 2023-10-16 19:17:11,513 django.server Thread-3 21932 basehttp basehttp.py 212 django.server log_message 12928 "GET /home HTTP/1.1" 200 31953
WARNING 2023-10-16 19:17:11,601 django.server Thread-3 21932 basehttp basehttp.py 212 django.server log_message 12928 "GET /static/css/test%20.css HTTP/1.1" 404 1800
INFO 2023-10-16 19:17:11,612 django.server Thread-4 20856 basehttp basehttp.py 212 django.server log_message 12928 "GET /static/css/home.css HTTP/1.1" 200 853
INFO 2023-10-16 19:17:11,914 django.server Thread-4 20856 basehttp basehttp.py 212 django.server log_message 12928 "GET /static/images/favicon.png HTTP/1.1" 200 1030
INFO 2023-10-16 19:17:14,661 django.server Thread-5 22292 basehttp basehttp.py 212 django.server log_message 12928 "GET /admin_home/ HTTP/1.1" 200 19234
INFO 2023-10-16 19:17:19,394 django.server Thread-5 22292 basehttp basehttp.py 212 django.server log_message 12928 "GET /admin_home/ HTTP/1.1" 200 19233
INFO 2023-10-16 19:18:19,833 django.server Thread-6 17048 basehttp basehttp.py 212 django.server log_message 12928 "GET /admin_home/ HTTP/1.1" 200 19234
INFO 2023-10-16 19:18:20,184 django.server Thread-6 17048 basehttp basehttp.py 212 django.server log_message 12928 "GET /static/images/favicon.png HTTP/1.1" 304 0
INFO 2023-10-16 19:18:22,238 django.server Thread-6 17048 basehttp basehttp.py 212 django.server log_message 12928 "GET /admin_home/ HTTP/1.1" 200 19234
INFO 2023-10-16 19:18:26,061 django.server Thread-7 10456 basehttp basehttp.py 212 django.server log_message 12928 "GET /admin_home/ HTTP/1.1" 200 19233
INFO 2023-10-16 19:18:31,548 django.server Thread-7 10456 basehttp basehttp.py 212 django.server log_message 12928 "GET /admin_home/ HTTP/1.1" 200 19234
INFO 2023-10-16 19:18:32,196 django.server Thread-7 10456 basehttp basehttp.py 212 django.server log_message 12928 "GET /admin_home/ HTTP/1.1" 200 19233
INFO 2023-10-16 19:18:33,856 django.server Thread-8 15872 basehttp basehttp.py 212 django.server log_message 12928 "GET /admin_home/ HTTP/1.1" 200 19233
INFO 2023-10-16 19:18:36,380 django.server Thread-8 15872 basehttp basehttp.py 212 django.server log_message 12928 "GET /home HTTP/1.1" 200 31951
INFO 2023-10-16 19:18:36,453 django.server Thread-8 15872 basehttp basehttp.py 212 django.server log_message 12928 "GET /static/css/home.css HTTP/1.1" 304 0
WARNING 2023-10-16 19:18:36,492 django.server Thread-9 15324 basehttp basehttp.py 212 django.server log_message 12928 "GET /static/css/test%20.css HTTP/1.1" 404 1800
INFO 2023-10-17 12:25:53,196 django.utils.autoreload MainThread 1364 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 17628 Watching for file changes with StatReloader
INFO 2023-10-17 12:48:23,409 django.utils.autoreload MainThread 1364 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 17628 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py changed, reloading.
INFO 2023-10-17 13:08:17,037 django.utils.autoreload MainThread 19048 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 14736 Watching for file changes with StatReloader
INFO 2023-10-17 13:08:26,524 django.server Thread-1 10688 basehttp basehttp.py 212 django.server log_message 14736 "POST /login_user/ HTTP/1.1" 302 0
INFO 2023-10-17 13:08:26,776 django.server Thread-1 10688 basehttp basehttp.py 212 django.server log_message 14736 "GET /home HTTP/1.1" 200 32249
INFO 2023-10-17 13:08:26,897 django.server Thread-1 10688 basehttp basehttp.py 212 django.server log_message 14736 "GET /static/css/test.css HTTP/1.1" 200 2829
INFO 2023-10-17 13:08:26,929 django.server Thread-1 10688 basehttp basehttp.py 212 django.server log_message 14736 "GET /static/css/home.css HTTP/1.1" 200 853
WARNING 2023-10-17 13:08:27,012 django.server Thread-2 13992 basehttp basehttp.py 212 django.server log_message 14736 "GET /static/css/test%20.css HTTP/1.1" 404 1800
INFO 2023-10-17 13:08:27,329 django.server Thread-3 21100 basehttp basehttp.py 212 django.server log_message 14736 "GET /static/js/specialization_filter.js HTTP/1.1" 200 1412
INFO 2023-10-17 13:08:28,604 django.server Thread-4 16796 basehttp basehttp.py 212 django.server log_message 14736 "GET /static/images/favicon.png HTTP/1.1" 200 1030
INFO 2023-10-17 13:08:34,157 django.server Thread-4 16796 basehttp basehttp.py 212 django.server log_message 14736 "GET /test_home/ HTTP/1.1" 200 12549
INFO 2023-10-17 13:08:39,379 django.server Thread-5 8416 basehttp basehttp.py 212 django.server log_message 14736 "GET /gradelevel_input/ HTTP/1.1" 200 9716
INFO 2023-10-17 13:08:39,579 django.server Thread-5 8416 basehttp basehttp.py 212 django.server log_message 14736 "GET /static/css/grade_level.css HTTP/1.1" 200 509
WARNING 2023-10-17 13:08:40,119 django.request Thread-5 8416 log log.py 241 django.request log_response 14736 Not Found: /favicon.ico
WARNING 2023-10-17 13:08:40,119 django.server Thread-5 8416 basehttp basehttp.py 212 django.server log_message 14736 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:08:41,087 django.request Thread-5 8416 log log.py 241 django.request log_response 14736 Not Found: /favicon.ico
WARNING 2023-10-17 13:08:41,089 django.server Thread-5 8416 basehttp basehttp.py 212 django.server log_message 14736 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:08:46,004 django.server Thread-5 8416 basehttp basehttp.py 212 django.server log_message 14736 "GET /start_test/ HTTP/1.1" 302 0
INFO 2023-10-17 13:08:46,147 django.server Thread-5 8416 basehttp basehttp.py 212 django.server log_message 14736 "GET /question/1/ HTTP/1.1" 200 13117
INFO 2023-10-17 13:09:17,095 django.server Thread-6 15688 basehttp basehttp.py 212 django.server log_message 14736 "GET /next_test/1/ HTTP/1.1" 200 12789
INFO 2023-10-17 13:10:19,114 django.utils.autoreload MainThread 19048 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 14736 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py changed, reloading.
INFO 2023-10-17 13:10:21,432 django.utils.autoreload MainThread 14112 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 16944 Watching for file changes with StatReloader
INFO 2023-10-17 13:10:25,181 django.utils.autoreload MainThread 14112 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 16944 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py changed, reloading.
INFO 2023-10-17 13:10:27,834 django.utils.autoreload MainThread 18452 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 2744 Watching for file changes with StatReloader
INFO 2023-10-17 13:10:36,870 django.server Thread-1 19776 basehttp basehttp.py 212 django.server log_message 2744 "GET /next_test/2/ HTTP/1.1" 200 12789
INFO 2023-10-17 13:10:38,744 django.server Thread-1 19776 basehttp basehttp.py 212 django.server log_message 2744 "GET /next_test/3/ HTTP/1.1" 200 12788
INFO 2023-10-17 13:10:43,328 django.server Thread-1 19776 basehttp basehttp.py 212 django.server log_message 2744 "GET /next_test/4/ HTTP/1.1" 302 0
INFO 2023-10-17 13:10:43,545 django.server Thread-1 19776 basehttp basehttp.py 212 django.server log_message 2744 "GET /test_overview/ HTTP/1.1" 200 14634
INFO 2023-10-17 13:10:49,145 django.server Thread-2 7872 basehttp basehttp.py 212 django.server log_message 2744 "GET /question/1/ HTTP/1.1" 200 12829
INFO 2023-10-17 13:10:51,795 django.server Thread-2 7872 basehttp basehttp.py 212 django.server log_message 2744 "POST /submit_question/1/ HTTP/1.1" 200 13096
INFO 2023-10-17 13:10:54,387 django.server Thread-2 7872 basehttp basehttp.py 212 django.server log_message 2744 "POST /submit_question/2/ HTTP/1.1" 200 13096
INFO 2023-10-17 13:10:56,114 django.server Thread-2 7872 basehttp basehttp.py 212 django.server log_message 2744 "POST /submit_question/3/ HTTP/1.1" 200 13096
INFO 2023-10-17 13:10:57,714 django.server Thread-2 7872 basehttp basehttp.py 212 django.server log_message 2744 "POST /submit_question/4/ HTTP/1.1" 200 13096
INFO 2023-10-17 13:10:59,962 django.server Thread-3 10360 basehttp basehttp.py 212 django.server log_message 2744 "POST /submit_question/5/ HTTP/1.1" 200 13095
INFO 2023-10-17 13:12:57,802 django.utils.autoreload MainThread 18452 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 2744 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py changed, reloading.
INFO 2023-10-17 13:13:00,429 django.utils.autoreload MainThread 19404 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 7728 Watching for file changes with StatReloader
INFO 2023-10-17 13:13:05,429 django.server Thread-1 10476 basehttp basehttp.py 212 django.server log_message 7728 "POST /submit_question/5/ HTTP/1.1" 200 13095
INFO 2023-10-17 13:13:07,719 django.server Thread-1 10476 basehttp basehttp.py 212 django.server log_message 7728 "POST /submit_question/6/ HTTP/1.1" 200 13094
INFO 2023-10-17 13:13:13,907 django.server Thread-1 10476 basehttp basehttp.py 212 django.server log_message 7728 "POST /submit_question/4/ HTTP/1.1" 302 0
INFO 2023-10-17 13:13:14,125 django.server Thread-1 10476 basehttp basehttp.py 212 django.server log_message 7728 "GET /test_overview/ HTTP/1.1" 200 14861
INFO 2023-10-17 13:13:17,887 django.server Thread-1 10476 basehttp basehttp.py 212 django.server log_message 7728 "GET /submit_test/ HTTP/1.1" 302 0
INFO 2023-10-17 13:13:18,009 django.server Thread-1 10476 basehttp basehttp.py 212 django.server log_message 7728 "GET /home HTTP/1.1" 200 32244
WARNING 2023-10-17 13:13:18,110 django.server Thread-1 10476 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/css/test%20.css HTTP/1.1" 404 1800
INFO 2023-10-17 13:13:26,434 django.server Thread-2 18224 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin_home/ HTTP/1.1" 200 19234
INFO 2023-10-17 13:13:34,179 django.server Thread-3 11852 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin_home/ HTTP/1.1" 200 19234
INFO 2023-10-17 13:13:37,844 django.server Thread-3 11852 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin HTTP/1.1" 301 0
INFO 2023-10-17 13:13:38,239 django.server Thread-4 10172 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/ HTTP/1.1" 200 20795
INFO 2023-10-17 13:13:38,329 django.server Thread-4 10172 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/css/base.css HTTP/1.1" 200 21207
INFO 2023-10-17 13:13:38,481 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
INFO 2023-10-17 13:13:38,482 django.server Thread-5 20704 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
INFO 2023-10-17 13:13:38,647 django.server Thread-7 9444 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2023-10-17 13:13:38,672 django.server Thread-8 264 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
INFO 2023-10-17 13:13:38,795 django.server Thread-8 264 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
INFO 2023-10-17 13:13:38,797 django.server Thread-7 9444 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2023-10-17 13:13:38,813 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2023-10-17 13:13:38,966 django.server Thread-5 20704 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
WARNING 2023-10-17 13:13:39,199 django.request Thread-6 8008 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:39,201 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:13:40,182 django.request Thread-6 8008 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:40,183 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:13:41,201 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/userresponse/ HTTP/1.1" 200 24583
INFO 2023-10-17 13:13:41,400 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6566
INFO 2023-10-17 13:13:41,473 django.server Thread-8 264 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2023-10-17 13:13:41,581 django.server Thread-4 10172 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/core.js HTTP/1.1" 200 5682
INFO 2023-10-17 13:13:41,664 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
INFO 2023-10-17 13:13:41,692 django.server Thread-5 20704 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-10-17 13:13:41,693 django.server Thread-9 14844 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8943
INFO 2023-10-17 13:13:41,697 django.server Thread-7 9444 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 292458
INFO 2023-10-17 13:13:41,819 django.server Thread-8 264 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2023-10-17 13:13:41,831 django.server Thread-4 10172 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2023-10-17 13:13:41,921 django.server Thread-4 10172 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2023-10-17 13:13:41,948 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
INFO 2023-10-17 13:13:42,045 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
WARNING 2023-10-17 13:13:42,300 django.request Thread-6 8008 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:42,300 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:13:43,282 django.request Thread-6 8008 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:43,293 django.server Thread-6 8008 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
INFO 2023-10-17 13:13:48,096 django.server Thread-10 10568 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20342
INFO 2023-10-17 13:13:48,263 django.server Thread-10 10568 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:13:48,735 django.request Thread-10 10568 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:48,744 django.server Thread-10 10568 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:13:49,684 django.request Thread-10 10568 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:49,688 django.server Thread-10 10568 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:13:51,229 django.server Thread-10 10568 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/questionset/4/change/ HTTP/1.1" 200 22428
INFO 2023-10-17 13:13:51,326 django.server Thread-10 10568 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/css/forms.css HTTP/1.1" 200 9047
INFO 2023-10-17 13:13:51,386 django.server Thread-11 14904 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2023-10-17 13:13:51,489 django.server Thread-13 10144 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2023-10-17 13:13:51,529 django.server Thread-12 10796 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-10-17 13:13:51,667 django.server Thread-12 10796 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11900
INFO 2023-10-17 13:13:51,692 django.server Thread-13 10144 basehttp basehttp.py 212 django.server log_message 7728 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
WARNING 2023-10-17 13:13:52,004 django.request Thread-13 10144 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:52,009 django.server Thread-13 10144 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:13:52,899 django.request Thread-13 10144 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:13:52,899 django.server Thread-13 10144 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:14:01,368 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20343
WARNING 2023-10-17 13:14:02,869 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:02,869 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:14:03,898 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/questionset/1/change/ HTTP/1.1" 200 22428
INFO 2023-10-17 13:14:04,131 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:14:04,594 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:04,614 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:14:05,504 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:05,504 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:14:06,703 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20343
INFO 2023-10-17 13:14:08,086 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/questionset/2/change/ HTTP/1.1" 200 22428
INFO 2023-10-17 13:14:08,403 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:14:08,762 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:08,764 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:14:09,705 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:09,713 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:14:10,070 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20343
INFO 2023-10-17 13:14:11,558 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/questionset/3/change/ HTTP/1.1" 200 22428
INFO 2023-10-17 13:14:11,825 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:14:11,885 django.request Thread-15 20884 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
INFO 2023-10-17 13:14:11,893 django.server Thread-15 20884 basehttp basehttp.py 81 django.server handle_error 7728 - Broken pipe from ('127.0.0.1', 5303)
WARNING 2023-10-17 13:14:12,268 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:12,278 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:14:13,193 django.request Thread-14 15808 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:13,198 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:14:13,379 django.server Thread-14 15808 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20344
INFO 2023-10-17 13:14:14,858 django.server Thread-16 12356 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/questionset/4/change/ HTTP/1.1" 200 22428
WARNING 2023-10-17 13:14:15,009 django.request Thread-17 6008 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
INFO 2023-10-17 13:14:15,027 django.server Thread-17 6008 basehttp basehttp.py 81 django.server handle_error 7728 - Broken pipe from ('127.0.0.1', 5312)
INFO 2023-10-17 13:14:15,140 django.server Thread-16 12356 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:14:15,578 django.request Thread-16 12356 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:15,580 django.server Thread-16 12356 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:14:16,461 django.request Thread-16 12356 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:16,464 django.server Thread-16 12356 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:14:17,349 django.server Thread-16 12356 basehttp basehttp.py 212 django.server log_message 7728 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20343
WARNING 2023-10-17 13:14:18,792 django.request Thread-16 12356 log log.py 241 django.request log_response 7728 Not Found: /favicon.ico
WARNING 2023-10-17 13:14:18,793 django.server Thread-16 12356 basehttp basehttp.py 212 django.server log_message 7728 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:19:05,895 django.utils.autoreload MainThread 19404 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 7728 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:19:08,396 django.utils.autoreload MainThread 16572 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 8052 Watching for file changes with StatReloader
ERROR 2023-10-17 13:19:11,376 django.request Thread-1 16780 log log.py 241 django.request log_response 8052 Internal Server Error: /admin/assessment/questionset/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
KeyError: '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: QuestionSet has no field named '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\test\utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 336, in result_list
    "results": list(results(cl)),
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\contrib\admin\utils.py", line 285, in lookup_field
    value = attr()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py", line 30, in __str__
    return f"id:{self.set_id} n_questions:{self.n_questions} is_complited:{self.is_complited} score:{self.score}"#str(self.set_id)
AttributeError: 'QuestionSet' object has no attribute 'is_complited'
ERROR 2023-10-17 13:19:11,529 django.server Thread-1 16780 basehttp basehttp.py 212 django.server log_message 8052 "GET /admin/assessment/questionset/ HTTP/1.1" 500 442566
WARNING 2023-10-17 13:19:13,450 django.request Thread-1 16780 log log.py 241 django.request log_response 8052 Not Found: /favicon.ico
WARNING 2023-10-17 13:19:13,454 django.server Thread-1 16780 basehttp basehttp.py 212 django.server log_message 8052 "GET /favicon.ico HTTP/1.1" 404 17458
WARNING 2023-10-17 13:19:14,533 django.request Thread-1 16780 log log.py 241 django.request log_response 8052 Not Found: /favicon.ico
WARNING 2023-10-17 13:19:14,535 django.server Thread-1 16780 basehttp basehttp.py 212 django.server log_message 8052 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:19:21,851 django.utils.autoreload MainThread 16572 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 8052 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:19:26,480 django.utils.autoreload MainThread 16772 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 4892 Watching for file changes with StatReloader
INFO 2023-10-17 13:19:32,273 django.server Thread-1 15768 basehttp basehttp.py 212 django.server log_message 4892 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20516
INFO 2023-10-17 13:19:32,452 django.server Thread-1 15768 basehttp basehttp.py 212 django.server log_message 4892 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:19:33,151 django.request Thread-1 15768 log log.py 241 django.request log_response 4892 Not Found: /favicon.ico
WARNING 2023-10-17 13:19:33,153 django.server Thread-1 15768 basehttp basehttp.py 212 django.server log_message 4892 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:19:34,041 django.request Thread-1 15768 log log.py 241 django.request log_response 4892 Not Found: /favicon.ico
WARNING 2023-10-17 13:19:34,043 django.server Thread-1 15768 basehttp basehttp.py 212 django.server log_message 4892 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:20:06,103 django.utils.autoreload MainThread 16772 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 4892 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:20:08,158 django.utils.autoreload MainThread 7600 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 5100 Watching for file changes with StatReloader
INFO 2023-10-17 13:20:13,388 django.server Thread-1 2220 basehttp basehttp.py 212 django.server log_message 5100 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20451
INFO 2023-10-17 13:20:13,588 django.server Thread-1 2220 basehttp basehttp.py 212 django.server log_message 5100 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:20:13,973 django.request Thread-1 2220 log log.py 241 django.request log_response 5100 Not Found: /favicon.ico
WARNING 2023-10-17 13:20:13,979 django.server Thread-1 2220 basehttp basehttp.py 212 django.server log_message 5100 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:20:14,938 django.request Thread-1 2220 log log.py 241 django.request log_response 5100 Not Found: /favicon.ico
WARNING 2023-10-17 13:20:14,940 django.server Thread-1 2220 basehttp basehttp.py 212 django.server log_message 5100 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:20:38,572 django.utils.autoreload MainThread 7600 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 5100 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:20:40,753 django.utils.autoreload MainThread 12936 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 12344 Watching for file changes with StatReloader
INFO 2023-10-17 13:20:44,242 django.utils.autoreload MainThread 12936 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 12344 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:20:46,978 django.utils.autoreload MainThread 16476 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 10160 Watching for file changes with StatReloader
INFO 2023-10-17 13:20:48,979 django.server Thread-1 9560 basehttp basehttp.py 212 django.server log_message 10160 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20451
INFO 2023-10-17 13:20:49,123 django.server Thread-1 9560 basehttp basehttp.py 212 django.server log_message 10160 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:20:49,538 django.request Thread-1 9560 log log.py 241 django.request log_response 10160 Not Found: /favicon.ico
WARNING 2023-10-17 13:20:49,543 django.server Thread-1 9560 basehttp basehttp.py 212 django.server log_message 10160 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:20:50,503 django.request Thread-3 12460 log log.py 241 django.request log_response 10160 Not Found: /favicon.ico
WARNING 2023-10-17 13:20:50,504 django.server Thread-3 12460 basehttp basehttp.py 212 django.server log_message 10160 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:20:53,523 django.utils.autoreload MainThread 16476 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 10160 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:20:55,679 django.utils.autoreload MainThread 18308 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 2604 Watching for file changes with StatReloader
INFO 2023-10-17 13:21:14,678 django.utils.autoreload MainThread 18308 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 2604 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:21:18,458 django.utils.autoreload MainThread 10172 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 20096 Watching for file changes with StatReloader
INFO 2023-10-17 13:21:22,033 django.server Thread-1 9172 basehttp basehttp.py 81 django.server handle_error 20096 - Broken pipe from ('127.0.0.1', 5528)
INFO 2023-10-17 13:21:22,295 django.server Thread-2 15260 basehttp basehttp.py 212 django.server log_message 20096 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20473
INFO 2023-10-17 13:21:22,649 django.server Thread-2 15260 basehttp basehttp.py 212 django.server log_message 20096 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:21:23,863 django.request Thread-2 15260 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:23,868 django.server Thread-2 15260 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:21:24,883 django.request Thread-2 15260 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:24,885 django.server Thread-2 15260 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:21:47,407 django.server Thread-3 13076 basehttp basehttp.py 212 django.server log_message 20096 "GET /admin/assessment/userresponse/ HTTP/1.1" 200 25296
INFO 2023-10-17 13:21:47,588 django.server Thread-3 13076 basehttp basehttp.py 212 django.server log_message 20096 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:21:48,055 django.request Thread-3 13076 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:48,060 django.server Thread-3 13076 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:21:48,944 django.request Thread-3 13076 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:48,945 django.server Thread-3 13076 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:21:52,643 django.server Thread-4 3044 basehttp basehttp.py 212 django.server log_message 20096 "GET /admin/assessment/userresponse/ HTTP/1.1" 200 25296
INFO 2023-10-17 13:21:52,802 django.server Thread-4 3044 basehttp basehttp.py 212 django.server log_message 20096 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:21:53,260 django.request Thread-4 3044 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:53,261 django.server Thread-4 3044 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:21:54,195 django.request Thread-4 3044 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:21:54,202 django.server Thread-4 3044 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17459
INFO 2023-10-17 13:22:04,558 django.server Thread-5 20484 basehttp basehttp.py 212 django.server log_message 20096 "GET /admin/assessment/userresponse/ HTTP/1.1" 200 25296
INFO 2023-10-17 13:22:04,754 django.server Thread-5 20484 basehttp basehttp.py 212 django.server log_message 20096 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:22:05,360 django.request Thread-5 20484 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:22:05,377 django.server Thread-5 20484 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:22:06,226 django.request Thread-5 20484 log log.py 241 django.request log_response 20096 Not Found: /favicon.ico
WARNING 2023-10-17 13:22:06,228 django.server Thread-5 20484 basehttp basehttp.py 212 django.server log_message 20096 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:22:44,667 django.utils.autoreload MainThread 10172 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 20096 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:22:46,863 django.utils.autoreload MainThread 15576 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 2644 Watching for file changes with StatReloader
INFO 2023-10-17 13:22:49,452 django.server Thread-1 9972 basehttp basehttp.py 212 django.server log_message 2644 "GET /admin/assessment/userresponse/ HTTP/1.1" 200 24583
INFO 2023-10-17 13:22:49,644 django.server Thread-1 9972 basehttp basehttp.py 212 django.server log_message 2644 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-10-17 13:22:50,648 django.server Thread-1 9972 basehttp basehttp.py 212 django.server log_message 2644 "GET /admin/assessment/userresponse/ HTTP/1.1" 200 24583
WARNING 2023-10-17 13:22:50,773 django.request Thread-2 13884 log log.py 241 django.request log_response 2644 Not Found: /favicon.ico
INFO 2023-10-17 13:22:50,781 django.server Thread-2 13884 basehttp basehttp.py 81 django.server handle_error 2644 - Broken pipe from ('127.0.0.1', 5569)
INFO 2023-10-17 13:22:50,911 django.server Thread-1 9972 basehttp basehttp.py 212 django.server log_message 2644 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:22:51,263 django.request Thread-1 9972 log log.py 241 django.request log_response 2644 Not Found: /favicon.ico
WARNING 2023-10-17 13:22:51,263 django.server Thread-1 9972 basehttp basehttp.py 212 django.server log_message 2644 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:22:52,205 django.request Thread-1 9972 log log.py 241 django.request log_response 2644 Not Found: /favicon.ico
WARNING 2023-10-17 13:22:52,207 django.server Thread-1 9972 basehttp basehttp.py 212 django.server log_message 2644 "GET /favicon.ico HTTP/1.1" 404 17459
INFO 2023-10-17 13:23:06,047 django.utils.autoreload MainThread 15576 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 2644 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:23:09,547 django.utils.autoreload MainThread 16716 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 20380 Watching for file changes with StatReloader
INFO 2023-10-17 13:23:13,250 django.server Thread-1 3240 basehttp basehttp.py 212 django.server log_message 20380 "GET /admin/assessment/userresponse/ HTTP/1.1" 200 24814
INFO 2023-10-17 13:23:13,520 django.server Thread-1 3240 basehttp basehttp.py 212 django.server log_message 20380 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:23:14,957 django.request Thread-1 3240 log log.py 241 django.request log_response 20380 Not Found: /favicon.ico
WARNING 2023-10-17 13:23:14,962 django.server Thread-1 3240 basehttp basehttp.py 212 django.server log_message 20380 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:23:15,866 django.request Thread-1 3240 log log.py 241 django.request log_response 20380 Not Found: /favicon.ico
WARNING 2023-10-17 13:23:15,869 django.server Thread-1 3240 basehttp basehttp.py 212 django.server log_message 20380 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:23:26,298 django.utils.autoreload MainThread 16716 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 20380 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:23:29,353 django.utils.autoreload MainThread 7640 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 10820 Watching for file changes with StatReloader
INFO 2023-10-17 13:23:55,787 django.utils.autoreload MainThread 7640 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 10820 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:23:57,848 django.utils.autoreload MainThread 7484 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 14568 Watching for file changes with StatReloader
INFO 2023-10-17 13:24:00,761 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /admin/assessment/userresponse/ HTTP/1.1" 200 24813
INFO 2023-10-17 13:24:01,010 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:24:01,429 django.request Thread-1 1976 log log.py 241 django.request log_response 14568 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:01,438 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:24:02,358 django.request Thread-1 1976 log log.py 241 django.request log_response 14568 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:02,358 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:24:02,583 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20528
INFO 2023-10-17 13:24:02,753 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:24:03,233 django.request Thread-1 1976 log log.py 241 django.request log_response 14568 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:03,233 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:24:04,137 django.request Thread-1 1976 log log.py 241 django.request log_response 14568 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:04,140 django.server Thread-1 1976 basehttp basehttp.py 212 django.server log_message 14568 "GET /favicon.ico HTTP/1.1" 404 17458
INFO 2023-10-17 13:24:10,324 django.utils.autoreload MainThread 7484 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 14568 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:24:13,943 django.utils.autoreload MainThread 18384 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 19936 Watching for file changes with StatReloader
INFO 2023-10-17 13:24:47,034 django.utils.autoreload MainThread 18384 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 19936 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:24:49,615 django.utils.autoreload MainThread 8000 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 21100 Watching for file changes with StatReloader
INFO 2023-10-17 13:24:56,098 django.server Thread-1 11404 basehttp basehttp.py 212 django.server log_message 21100 "GET /admin/assessment/questionset/ HTTP/1.1" 200 20525
INFO 2023-10-17 13:24:56,267 django.server Thread-1 11404 basehttp basehttp.py 212 django.server log_message 21100 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-10-17 13:24:56,764 django.request Thread-1 11404 log log.py 241 django.request log_response 21100 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:56,766 django.server Thread-1 11404 basehttp basehttp.py 212 django.server log_message 21100 "GET /favicon.ico HTTP/1.1" 404 17459
WARNING 2023-10-17 13:24:57,679 django.request Thread-1 11404 log log.py 241 django.request log_response 21100 Not Found: /favicon.ico
WARNING 2023-10-17 13:24:57,680 django.server Thread-1 11404 basehttp basehttp.py 212 django.server log_message 21100 "GET /favicon.ico HTTP/1.1" 404 17459
INFO 2023-10-17 13:55:27,058 django.utils.autoreload MainThread 8000 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 21100 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\models.py changed, reloading.
INFO 2023-10-17 13:55:29,460 django.utils.autoreload MainThread 8032 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 11248 Watching for file changes with StatReloader
INFO 2023-10-17 14:20:30,105 django.utils.autoreload MainThread 8032 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 11248 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py changed, reloading.
INFO 2023-10-17 14:20:33,289 django.utils.autoreload MainThread 12924 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 16260 Watching for file changes with StatReloader
INFO 2023-10-17 14:20:46,353 django.utils.autoreload MainThread 12924 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 16260 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:20:51,551 django.utils.autoreload MainThread 7428 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 4268 Watching for file changes with StatReloader
INFO 2023-10-17 14:21:02,322 django.utils.autoreload MainThread 7428 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 4268 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:21:04,604 django.utils.autoreload MainThread 18372 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 15436 Watching for file changes with StatReloader
INFO 2023-10-17 14:21:11,086 django.utils.autoreload MainThread 18372 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 15436 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:21:16,744 django.utils.autoreload MainThread 14584 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 13372 Watching for file changes with StatReloader
INFO 2023-10-17 14:24:57,216 django.utils.autoreload MainThread 14584 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 13372 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:25:00,650 django.utils.autoreload MainThread 2924 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 20488 Watching for file changes with StatReloader
INFO 2023-10-17 14:26:52,090 django.utils.autoreload MainThread 2924 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 20488 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:26:58,739 django.utils.autoreload MainThread 21684 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 21692 Watching for file changes with StatReloader
INFO 2023-10-17 14:27:50,315 django.utils.autoreload MainThread 21684 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 21692 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\urls.py changed, reloading.
INFO 2023-10-17 14:27:53,953 django.utils.autoreload MainThread 21800 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 13792 Watching for file changes with StatReloader
INFO 2023-10-17 14:28:39,831 django.utils.autoreload MainThread 21800 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 13792 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\urls.py changed, reloading.
INFO 2023-10-17 14:28:42,419 django.utils.autoreload MainThread 10340 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 9572 Watching for file changes with StatReloader
INFO 2023-10-17 14:28:53,339 django.utils.autoreload MainThread 10340 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 9572 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:28:58,325 django.utils.autoreload MainThread 10164 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 21968 Watching for file changes with StatReloader
INFO 2023-10-17 14:29:02,959 django.server Thread-1 6708 basehttp basehttp.py 212 django.server log_message 21968 "GET /admin_report HTTP/1.1" 301 0
ERROR 2023-10-17 14:29:04,074 django.request Thread-2 1056 log log.py 241 django.request log_response 21968 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2053, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py", line 361, in admin_test_report
    scores_list.append(QuestionSet.objects.filter(score=score).count())
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'score' expected a number but got {'score': 3}.
ERROR 2023-10-17 14:29:04,267 django.server Thread-2 1056 basehttp basehttp.py 212 django.server log_message 21968 "GET /admin_report/ HTTP/1.1" 500 149360
WARNING 2023-10-17 14:29:05,704 django.request Thread-2 1056 log log.py 241 django.request log_response 21968 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:05,706 django.server Thread-2 1056 basehttp basehttp.py 212 django.server log_message 21968 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:29:06,941 django.request Thread-2 1056 log log.py 241 django.request log_response 21968 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:06,942 django.server Thread-2 1056 basehttp basehttp.py 212 django.server log_message 21968 "GET /favicon.ico HTTP/1.1" 404 17634
INFO 2023-10-17 14:29:32,762 django.utils.autoreload MainThread 10164 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 21968 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:29:35,025 django.utils.autoreload MainThread 21868 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 21792 Watching for file changes with StatReloader
ERROR 2023-10-17 14:29:37,003 django.request Thread-1 10828 log log.py 241 django.request log_response 21792 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2053, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py", line 361, in admin_test_report
    scores_list.append(QuestionSet.objects.filter(score=score).count())
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'score' expected a number but got {'score': 3}.
ERROR 2023-10-17 14:29:37,160 django.server Thread-1 10828 basehttp basehttp.py 212 django.server log_message 21792 "GET /admin_report/ HTTP/1.1" 500 149359
WARNING 2023-10-17 14:29:37,694 django.request Thread-1 10828 log log.py 241 django.request log_response 21792 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:37,694 django.server Thread-1 10828 basehttp basehttp.py 212 django.server log_message 21792 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:29:38,645 django.request Thread-1 10828 log log.py 241 django.request log_response 21792 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:38,645 django.server Thread-1 10828 basehttp basehttp.py 212 django.server log_message 21792 "GET /favicon.ico HTTP/1.1" 404 17633
INFO 2023-10-17 14:29:44,059 django.utils.autoreload MainThread 21868 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 21792 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:29:48,288 django.utils.autoreload MainThread 10648 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 3348 Watching for file changes with StatReloader
ERROR 2023-10-17 14:29:51,730 django.request Thread-1 2984 log log.py 241 django.request log_response 3348 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2053, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py", line 361, in admin_test_report
    scores_list.append(QuestionSet.objects.filter(score=score).count())
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'score' expected a number but got {'score': 3}.
ERROR 2023-10-17 14:29:51,752 django.request Thread-2 21688 log log.py 241 django.request log_response 3348 Internal Server Error: /admin_report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2053, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py", line 361, in admin_test_report
    scores_list.append(QuestionSet.objects.filter(score=score).count())
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'score' expected a number but got {'score': 3}.
INFO 2023-10-17 14:29:52,114 django.server Thread-1 2984 basehttp basehttp.py 81 django.server handle_error 3348 - Broken pipe from ('127.0.0.1', 44485)
ERROR 2023-10-17 14:29:52,114 django.server Thread-2 21688 basehttp basehttp.py 212 django.server log_message 3348 "GET /admin_report/ HTTP/1.1" 500 149360
WARNING 2023-10-17 14:29:53,800 django.request Thread-2 21688 log log.py 241 django.request log_response 3348 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:53,802 django.server Thread-2 21688 basehttp basehttp.py 212 django.server log_message 3348 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:29:54,855 django.request Thread-2 21688 log log.py 241 django.request log_response 3348 Not Found: /favicon.ico
WARNING 2023-10-17 14:29:54,855 django.server Thread-2 21688 basehttp basehttp.py 212 django.server log_message 3348 "GET /favicon.ico HTTP/1.1" 404 17633
INFO 2023-10-17 14:31:15,095 django.utils.autoreload MainThread 10648 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 3348 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\urls.py changed, reloading.
INFO 2023-10-17 14:31:17,123 django.utils.autoreload MainThread 15896 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 20592 Watching for file changes with StatReloader
INFO 2023-10-17 14:31:39,313 django.utils.autoreload MainThread 15896 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 20592 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\urls.py changed, reloading.
INFO 2023-10-17 14:31:44,193 django.utils.autoreload MainThread 12804 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 8004 Watching for file changes with StatReloader
INFO 2023-10-17 14:31:47,768 django.server Thread-1 3324 basehttp basehttp.py 212 django.server log_message 8004 "GET /report HTTP/1.1" 301 0
ERROR 2023-10-17 14:31:48,960 django.request Thread-2 12120 log log.py 241 django.request log_response 8004 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 208, in admin_report
    x=[set.score['score'] for set in sets],
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 208, in <listcomp>
    x=[set.score['score'] for set in sets],
TypeError: 'int' object is not subscriptable
ERROR 2023-10-17 14:31:49,147 django.server Thread-2 12120 basehttp basehttp.py 212 django.server log_message 8004 "GET /report/ HTTP/1.1" 500 90101
WARNING 2023-10-17 14:31:49,984 django.request Thread-2 12120 log log.py 241 django.request log_response 8004 Not Found: /favicon.ico
WARNING 2023-10-17 14:31:49,986 django.server Thread-2 12120 basehttp basehttp.py 212 django.server log_message 8004 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:31:50,917 django.request Thread-2 12120 log log.py 241 django.request log_response 8004 Not Found: /favicon.ico
WARNING 2023-10-17 14:31:50,944 django.server Thread-2 12120 basehttp basehttp.py 212 django.server log_message 8004 "GET /favicon.ico HTTP/1.1" 404 17633
INFO 2023-10-17 14:32:00,748 django.utils.autoreload MainThread 12804 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 8004 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:32:06,459 django.utils.autoreload MainThread 21700 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 22460 Watching for file changes with StatReloader
INFO 2023-10-17 14:32:18,596 django.server Thread-1 16968 basehttp basehttp.py 81 django.server handle_error 22460 - Broken pipe from ('127.0.0.1', 44540)
INFO 2023-10-17 14:32:18,601 django.server Thread-2 14836 basehttp basehttp.py 212 django.server log_message 22460 "GET /report/ HTTP/1.1" 200 3616654
INFO 2023-10-17 14:32:18,701 django.server Thread-3 22504 basehttp basehttp.py 212 django.server log_message 22460 "GET /static/css/test.css HTTP/1.1" 304 0
INFO 2023-10-17 14:32:20,860 django.server Thread-2 14836 basehttp basehttp.py 212 django.server log_message 22460 "GET /static/images/favicon.png HTTP/1.1" 304 0
INFO 2023-10-17 14:32:35,654 django.server Thread-4 2480 basehttp basehttp.py 212 django.server log_message 22460 "GET /report/ HTTP/1.1" 200 3616654
INFO 2023-10-17 14:34:15,627 django.utils.autoreload MainThread 21700 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 22460 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:34:17,961 django.utils.autoreload MainThread 22128 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 12792 Watching for file changes with StatReloader
INFO 2023-10-17 14:34:23,178 django.server Thread-1 1132 basehttp basehttp.py 212 django.server log_message 12792 "GET /report/ HTTP/1.1" 200 3616700
INFO 2023-10-17 14:35:28,308 django.utils.autoreload MainThread 22128 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 12792 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:35:30,532 django.utils.autoreload MainThread 20672 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 22308 Watching for file changes with StatReloader
INFO 2023-10-17 14:35:34,497 django.server Thread-1 10340 basehttp basehttp.py 81 django.server handle_error 22308 - Broken pipe from ('127.0.0.1', 44647)
INFO 2023-10-17 14:35:38,948 django.server Thread-2 7560 basehttp basehttp.py 212 django.server log_message 22308 "GET /report/ HTTP/1.1" 200 3616700
INFO 2023-10-17 14:36:04,615 django.utils.autoreload MainThread 20672 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 22308 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:36:06,766 django.utils.autoreload MainThread 10820 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 3324 Watching for file changes with StatReloader
INFO 2023-10-17 14:36:11,485 django.server Thread-1 21572 basehttp basehttp.py 212 django.server log_message 3324 "GET /report/ HTTP/1.1" 200 3616700
INFO 2023-10-17 14:38:44,809 django.utils.autoreload MainThread 10820 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 3324 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:38:47,140 django.utils.autoreload MainThread 1148 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 18000 Watching for file changes with StatReloader
INFO 2023-10-17 14:43:00,360 django.utils.autoreload MainThread 19156 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 13028 Watching for file changes with StatReloader
INFO 2023-10-17 14:43:12,612 django.server Thread-1 21656 basehttp basehttp.py 212 django.server log_message 13028 "GET /report/ HTTP/1.1" 200 3616700
INFO 2023-10-17 14:43:26,303 django.utils.autoreload MainThread 19156 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 13028 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:43:28,976 django.utils.autoreload MainThread 21340 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 19676 Watching for file changes with StatReloader
INFO 2023-10-17 14:43:35,193 django.server Thread-1 1256 basehttp basehttp.py 81 django.server handle_error 19676 - Broken pipe from ('127.0.0.1', 44852)
INFO 2023-10-17 14:43:35,232 django.server Thread-2 60 basehttp basehttp.py 212 django.server log_message 19676 "GET /report/ HTTP/1.1" 200 3616720
INFO 2023-10-17 14:44:04,761 django.utils.autoreload MainThread 21340 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 19676 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:44:06,678 django.utils.autoreload MainThread 17692 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 18456 Watching for file changes with StatReloader
ERROR 2023-10-17 14:44:10,313 django.request Thread-1 5748 log log.py 241 django.request log_response 18456 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 211, in admin_report
    text=[set.username for set in sets],
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 211, in <listcomp>
    text=[set.username for set in sets],
AttributeError: 'QuestionSet' object has no attribute 'username'
ERROR 2023-10-17 14:44:10,446 django.server Thread-1 5748 basehttp basehttp.py 212 django.server log_message 18456 "GET /report/ HTTP/1.1" 500 90584
WARNING 2023-10-17 14:44:10,996 django.request Thread-1 5748 log log.py 241 django.request log_response 18456 Not Found: /favicon.ico
WARNING 2023-10-17 14:44:10,996 django.server Thread-1 5748 basehttp basehttp.py 212 django.server log_message 18456 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:44:11,946 django.request Thread-1 5748 log log.py 241 django.request log_response 18456 Not Found: /favicon.ico
WARNING 2023-10-17 14:44:11,946 django.server Thread-1 5748 basehttp basehttp.py 212 django.server log_message 18456 "GET /favicon.ico HTTP/1.1" 404 17633
INFO 2023-10-17 14:44:35,756 django.utils.autoreload MainThread 17692 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 18456 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:44:38,430 django.utils.autoreload MainThread 17164 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 15700 Watching for file changes with StatReloader
ERROR 2023-10-17 14:44:43,264 django.request Thread-1 12676 log log.py 241 django.request log_response 15700 Internal Server Error: /report/
Traceback (most recent call last):
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py", line 217, in admin_report
    chart = fig.to_html()#full_html=False, include_plotlyjs=False
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\basedatatypes.py", line 3604, in to_html
    return pio.to_html(self, *args, **kwargs)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\io\_html.py", line 144, in to_html
    jdata = to_json_plotly(fig_dict.get("data", []))
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\plotly\io\_json.py", line 143, in to_json_plotly
    json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts), _swap_json
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\_plotly_utils\utils.py", line 59, in encode
    encoded_o = super(PlotlyJSONEncoder, self).encode(o)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\courseu\lib\site-packages\_plotly_utils\utils.py", line 136, in default
    return _json.JSONEncoder.default(self, obj)
  File "C:\Users\aky\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
ERROR 2023-10-17 14:44:43,434 django.server Thread-1 12676 basehttp basehttp.py 212 django.server log_message 15700 "GET /report/ HTTP/1.1" 500 145601
WARNING 2023-10-17 14:44:43,933 django.request Thread-1 12676 log log.py 241 django.request log_response 15700 Not Found: /favicon.ico
WARNING 2023-10-17 14:44:43,933 django.server Thread-1 12676 basehttp basehttp.py 212 django.server log_message 15700 "GET /favicon.ico HTTP/1.1" 404 17634
WARNING 2023-10-17 14:44:44,941 django.request Thread-1 12676 log log.py 241 django.request log_response 15700 Not Found: /favicon.ico
WARNING 2023-10-17 14:44:44,957 django.server Thread-1 12676 basehttp basehttp.py 212 django.server log_message 15700 "GET /favicon.ico HTTP/1.1" 404 17633
INFO 2023-10-17 14:45:44,273 django.utils.autoreload MainThread 17164 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 15700 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:45:46,747 django.utils.autoreload MainThread 11248 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 4368 Watching for file changes with StatReloader
INFO 2023-10-17 14:45:52,684 django.server Thread-1 5100 basehttp basehttp.py 81 django.server handle_error 4368 - Broken pipe from ('127.0.0.1', 44907)
INFO 2023-10-17 14:45:52,700 django.server Thread-2 19160 basehttp basehttp.py 212 django.server log_message 4368 "GET /report/ HTTP/1.1" 200 3616782
INFO 2023-10-17 14:46:10,491 django.utils.autoreload MainThread 11248 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 4368 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\website\views.py changed, reloading.
INFO 2023-10-17 14:46:12,780 django.utils.autoreload MainThread 12368 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 492 Watching for file changes with StatReloader
INFO 2023-10-17 14:47:00,557 django.server Thread-1 11116 basehttp basehttp.py 212 django.server log_message 492 "GET /report/ HTTP/1.1" 200 3616860
INFO 2023-10-17 14:49:37,879 django.utils.autoreload MainThread 12368 autoreload autoreload.py 266 django.utils.autoreload trigger_reload 492 C:\Users\aky\AppData\Local\Programs\Python\Python38\course-u\course-u\assessment\views.py changed, reloading.
INFO 2023-10-17 14:49:41,176 django.utils.autoreload MainThread 10936 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 15932 Watching for file changes with StatReloader
